In [1]:
import tensorflow as tf
import numpy as np

In [5]:
# create a numpy array
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)
print('-------------')

[0 1 2 3 4 5 6 7 8 9]
(10,)
-------------


In [6]:
# convert from numpy array to tensor
arr_tf = tf.convert_to_tensor(arr_np)
print(arr_tf)
print(arr_tf.shape)
print('--------------')

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
(10,)
--------------


In [7]:
# convert from tensor to numpy array
arr_np_back = arr_tf.numpy()
print(arr_np_back)
print(arr_np_back.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [15]:
#Common attributes
import numpy as np

# tao list
l = list(range(1,4))

list1D = [1,2,3]

list2D = [[1,2],[3,4],[5,6]]

list3D = [[[1,6],[2,2],[3,4]],
          [[4,7],[5,3],[6,9]],
          [[7,7],[8,2],[9,3]]]
# tao ndarray
data = np.array(l)
data1 = np.array(list1D)
data2 = np.array(list2D)
data3 = np.array(list3D)

print(data)
print(data1)
print(data2)
print(data3)

[1 2 3]
[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[[1 6]
  [2 2]
  [3 4]]

 [[4 7]
  [5 3]
  [6 9]]

 [[7 7]
  [8 2]
  [9 3]]]


In [17]:
#Thay doi gia tri phan tu
import numpy as np

#Create list
l = list(range(1,4))

#tao ndarray
data = np.array(l)
print(data)
data[0] = 8
print(data)

[1 2 3]
[8 2 3]


In [19]:
# tao mot numpy array
# voi phan tu la 0
import numpy as np
# shape: 2 dong , 3 cot
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# tao mot numpy array voi
# numpy.ones(shape)
#shape: 2 dong 3 cot
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


In [23]:
#tao array
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


In [25]:
# tao arrray voi duong cheo la so 1

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#phan tu co gia tri ngau nhien
arr = np.random.random((2,3))
print(arr)

[[0.28661374 0.47335996 0.26492827]
 [0.14078698 0.61797128 0.27597937]]


In [28]:
arr = np.array(5)
print(arr)

condition = arr < 3
out =np.where(condition, arr, arr*2)

print(condition)
print(out)

5
False
10


In [29]:
arr = np.array([[1,2],[3,4]])
out = arr.flatten()

print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
# tao list
l =[[1,2,3],
    [4,5,6]]
# Tao ndarray
data = np.array(l)
print('data\n', data)
print('data shape\n', data.shape)

#reshape
data_rs = np.reshape(data,(3,2))
print('data_rs\n', data_rs)
print('data_rs shape\n'. data_rs)